services:
  iventoy:
    image: ziggyds/iventoy:latest
    container_name: iventoy
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ./image:/app/iso   # 本地目录挂载（相对路径）
      - ./data:/app/data # 本地目录挂载（相对路径）
    environment:
      - AUTO_START_PXE=true