services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=1000
      - UMASK=022
    volumes:
      - /home/docker/alist:/opt/alist/data
    restart: always