services:
  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    ports:
      - "42367:80"
      - "81:81"
      - "58467:443"
    volumes:
      - /home/docker/nginx_proxy_manager/data:/data
      - /home/docker/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    restart: always